openapi: 3.0.0
info:
  title: My Laravel API
  description: API documentation for Laravel application
  version: 1.0.0
  contact:
    name: Your Name
    url: https://yourwebsite.com
    email: your.email@example.com

servers:
  - url: 'http://localhost/api'
    description: Local development server

paths:
  /api/users:
    get:
      tags:
        - Users
      summary: Get all users
      description: Retrieve all users in the system
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '400':
          description: Bad request

  /api/users/{id}:
    get:
      tags:
        - Users
      summary: Get a user by ID
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the user
          schema:
            type: integer
      responses:
        '200':
          description: A user object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: John Doe
        email:
          type: string
          example: john@example.com
      required:
        - id
        - name
        - email
